package: demo_fullpage
version: '1.0.0beta'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/demo_fullpage

page:
    title: Fullpage-Demo
    perm: demo_fullpage[]
    pjax: true
    subpages:
        install: { title: 'translate:title' }
        settings: { title: 'translate:title_config' }

requires:
    packages:
        backup: '>=2.0.4'
        structure/content: '>=2.3.0'
    redaxo: '>=5.3.0'
    php: '>=5.5'
