package: demo_fullpage
version: 2.0.8
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_fullpage'
page:
    title: 'translate:demo_fullpage_title'
    perm: 'demo_fullpage[]'
    pjax: true
    icon: 'rex-icon fa-rocket'
    subpages:
        install: { title: 'translate:demo_fullpage_title', icon: 'rex-icon fa-rocket' }
        settings: { title: 'translate:demo_fullpage_settings', icon: 'rex-icon fa-wrench' }
        themes: { title: 'translate:demo_fullpage_themes', subPath: THEMES.md, icon: 'rex-icon fa-desktop' }
        changelog: { title: 'translate:demo_fullpage_changelog', subPath: CHANGELOG.md, icon: 'rex-icon fa-list', itemClass: pull-right, linkClass: btn-default }
requires:
    php:
        version: '>=7.4, <8.3'
    redaxo: ^5.13.0
    packages:
        backup: ^2.8.0
        be_style: ^3.0.1
        structure/content: ^2.13.2
default_config:
    theme: coffee
    logo: ''
    autoscrolling: 1
    showscrollbar: 0
    responsivewidth: 1200
    responsiveheight: 750
    scrollingspeed: 800
    shownavigation: 1
    shownavigationtooltip: 1
    navigationposition: right
    showslidearrows: 1
    showslidenavigation: 1
    slidenavigationposition: bottom
    usesubcategories: 1
console_commands:
    'demo_fullpage:dump_files': rex_command_demo_fullpage_dumpfiles
    'demo_fullpage:dump_tables': rex_command_demo_fullpage_dumptables
    'demo_fullpage:install': rex_command_demo_fullpage_install
setup:
    installSequence:
        - backup
        - structure/content
    dbimport:
        - demo_fullpage.sql
    fileimport:
        - demo_fullpage.tar.gz
