package: demo_fullpage
version: 1.1.0beta
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_fullpage'

page:
    title: 'translate:title'
    perm: 'demo_fullpage[]'
    pjax: true
    icon: 'rex-icon fa-rocket'
    subpages:
        install: { title: 'translate:title', icon: 'rex-icon fa-rocket' }
        settings: { title: 'translate:settings', icon: 'rex-icon fa-wrench' }
        info: { title: 'translate:info' }

requires:
    packages:
        backup: '>=2.0.4'
        structure/content: '>=2.3.0'
    redaxo: '>=5.3.0'
    php: '>=5.6'

system_plugins:
    - documentation
