package: demo_fullpage
version: 2.0.0
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_fullpage'
page:
    title: 'translate:demo_fullpage_title'
    perm: 'demo_fullpage[]'
    pjax: true
    icon: 'rex-icon fa-rocket'
    subpages:
        install: { title: 'translate:demo_fullpage_title', icon: 'rex-icon fa-rocket' }
        settings: { title: 'translate:demo_fullpage_settings', icon: 'rex-icon fa-wrench' }
        themes: { title: 'translate:demo_fullpage_themes', icon: 'rex-icon fa-desktop' }
requires:
    packages:
        backup: ^2.3.0
        structure/content: ^2.7.0
    redaxo: ^5.12.0
console_commands:
    'demo_fullpage:install': rex_command_demo_fullpage_install
setup:
    installSequence:
        - backup
        - structure/content
    dbimport:
        - demo_fullpage.sql
    fileimport:
        - demo_fullpage.tar.gz
